NAME_PROG=bdit
NAME_LIB=lib$(NAME_PROG)
SRC=block_device_integrity_tester.cpp
CPP=g++
CXXFLAGS=-std=c++11 -g -I$(INCLUDE_DIR)

$(NAME_LIB).a:
	$(CPP) 

$(NAME_LIB): $(NAME_LIB).a $(NAME_LIB).so
	

$(NAME_PROG): $(NAME_LIB)
	$(CPP) $(CXXFLAGS) -o $(OUTPUT) $(SRC)

all: $(NAME_PROG)

clean:
	rm -f $(OUTPUT) *.o

.PHONY: all clean

